from app.core.errors import AppException


class EmbeddingError(AppException):
    """Base exception for all Embedding Gateway errors."""

    def __init__(
        self,
        detail: str = "Embedding service encountered an unexpected error.",
        status_code: int = 500,
        internal_error: str | None = None,
    ) -> None:
        super().__init__(status_code=status_code, detail=detail)
        self.internal_error = internal_error

    def __str__(self) -> str:
        if self.internal_error:
            return f"{self.detail} (Internal: {self.internal_error})"
        return self.detail


class EmbeddingConfigurationError(EmbeddingError):
    """Raised when embedding provider configuration, credentials, or settings are missing or invalid."""

    def __init__(
        self,
        detail: str = "Embedding service configuration is invalid or provider is unsupported.",
        internal_error: str | None = None,
    ) -> None:
        super().__init__(detail=detail, status_code=500, internal_error=internal_error)


class EmbeddingProviderError(EmbeddingError):
    """Raised when an embedding provider fails to process an embedding request."""

    def __init__(
        self,
        detail: str = "Embedding could not be generated by provider.",
        status_code: int = 502,
        internal_error: str | None = None,
    ) -> None:
        super().__init__(detail=detail, status_code=status_code, internal_error=internal_error)
