import logging
from typing import Optional

from app.core.config import Settings, settings as default_settings
from app.embeddings.errors import EmbeddingConfigurationError, EmbeddingError, EmbeddingProviderError
from app.embeddings.interfaces import BaseEmbeddingProvider
from app.embeddings.providers.mock import MockEmbeddingProvider
from app.embeddings.schemas import (
    EmbeddingBatchRequest,
    EmbeddingBatchResponse,
    EmbeddingRequest,
    EmbeddingResponse,
)

logger = logging.getLogger(__name__)


class EmbeddingGateway:
    """Stateless Embedding Gateway for provider dispatch, request normalization, and error translation."""

    def __init__(
        self,
        provider: Optional[BaseEmbeddingProvider] = None,
        settings: Optional[Settings] = None,
    ) -> None:
        self._settings = settings or default_settings
        self._provider = provider or self._resolve_provider(self._settings)

    @classmethod
    def _resolve_provider(cls, settings: Settings) -> BaseEmbeddingProvider:
        provider_name = (settings.EMBEDDING_PROVIDER or "mock").strip().lower()

        if provider_name in ("mock", "test"):
            return MockEmbeddingProvider(
                default_model=settings.EMBEDDING_MODEL or "mock-embedding",
                default_dimensions=settings.EMBEDDING_DIMENSIONS or 384,
            )

        raise EmbeddingConfigurationError(
            detail=f"Unsupported embedding provider '{settings.EMBEDDING_PROVIDER}'.",
            internal_error=f"Provider '{settings.EMBEDDING_PROVIDER}' is not recognized.",
        )

    async def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        """Executes a single embedding request through the configured provider with default fallbacks."""
        effective_model = request.model or self._settings.EMBEDDING_MODEL
        effective_dims = request.dimensions or self._settings.EMBEDDING_DIMENSIONS

        normalized_request = EmbeddingRequest(
            input=request.input,
            model=effective_model,
            dimensions=effective_dims,
        )

        try:
            return await self._provider.embed(normalized_request)
        except EmbeddingError:
            raise
        except Exception as exc:
            logger.exception("Embedding generation failed unexpectedly: %s", exc)
            raise EmbeddingProviderError(
                detail="Embedding could not be generated by provider.",
                internal_error=str(exc),
            ) from exc

    async def embed_batch(self, request: EmbeddingBatchRequest) -> EmbeddingBatchResponse:
        """Executes a batch embedding request through the configured provider with default fallbacks."""
        effective_model = request.model or self._settings.EMBEDDING_MODEL
        effective_dims = request.dimensions or self._settings.EMBEDDING_DIMENSIONS

        normalized_batch = EmbeddingBatchRequest(
            inputs=request.inputs,
            model=effective_model,
            dimensions=effective_dims,
        )

        try:
            return await self._provider.embed_batch(normalized_batch)
        except EmbeddingError:
            raise
        except Exception as exc:
            logger.exception("Batch embedding generation failed unexpectedly: %s", exc)
            raise EmbeddingProviderError(
                detail="Batch embeddings could not be generated by provider.",
                internal_error=str(exc),
            ) from exc

    @property
    def provider(self) -> BaseEmbeddingProvider:
        """Returns the active embedding provider instance."""
        return self._provider


def get_embedding_gateway() -> EmbeddingGateway:
    """Dependency provider factory returning a stateless EmbeddingGateway instance."""
    return EmbeddingGateway()
